#ifndef _RONIN_RAT_ERRNO_H_
#define _RONIN_RAT_ERRNO_H_

#define RONIN_RAT_ERRNO_MAX		-6
#define RONIN_RAT_ERRNO_MALLOC		-5
#define RONIN_RAT_ERRNO_ARG_TYPE	-4
#define RONIN_RAT_ERRNO_FUNC_ARGS	-3
#define RONIN_RAT_ERRNO_FUNC		-2
#define RONIN_RAT_ERRNO_SERVICE		-1
#define RONIN_RAT_SUCCESS		0

#endif
